import { Box, Button, Input } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Fortedges | App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box fontSize="70px" color="others.cyan">
          Hello World
        </Box>
        <Button size="sm" variant="outline">
          1
        </Button>
        <Box w="900px" px="200px">
          <Input size="sm" placeholder="something" />
        </Box>
      </main>
    </div>
  );
}
